### ISSUE TITLE
`process.env.npm_lifecycle_event` doesn't get set when running through a hook

### ISSUE THREAD

**Issue by bebraw** [sturdynut/git-prepush-hook#1]
I'm not sure if this is by design but for some reason `npm_lifecycle_event` doesn't get set. My [boilerplate](https://survivejs.github.io/react-component-boilerplate/) happens to depend on that. I managed to work around the problem. If it's correct behavior, it would be good to document at least.

**Comment by sturdynut** [comment]
Hey @bebraw, interesting...I thought NPM would have handled that.  Maybe i'm not completely understanding, can you show me where you are working around this in your boilerplate?  That might help me understand what I can do to fix.  Thanks.

**Comment by bebraw** [comment]
I do a check like `if (TARGET === 'test' || TARGET === 'tdd' || !TARGET) {`. That last one matches for the hook given `TARGET` is `undefined` in that case. `TARGET` is set like this: `const TARGET = process.env.npm_lifecycle_event;`.

It's likely easy to set up a little test case. You'll need something like this:

``` javascript
const TARGET = process.env.npm_lifecycle_event;

// you could assert now that TARGET matches hook name
console.log(TARGET);
```

**Comment by sturdynut** [comment]
I see what's going on, but I'm not sure if I can fix it.  The prepush hook is being added via [https://github.com/nlf/git-validate](https://github.com/nlf/git-validate), which simply writes to the package.json file.  Do you have any idea what might fix that behavior?

**Comment by bebraw** [comment]
Perhaps it would make sense to push the issue upstream if it cannot be resolved here? It's kind of expected that npm env variables get set when you are executing scripts through npm after all.

**Comment by sturdynut** [comment]
I've opened an issue with git-validate here:  [https://github.com/nlf/git-validate/issues/39](https://github.com/nlf/git-validate/issues/39).  I'll continue to monitor and fix as soon as I can.

**Comment by sturdynut** [comment]
@bebraw - Not sure if this is still an issue for you, but I may have found something.  I created a test project and found that apparently `process.env.npm_lifecycle_event` is not set in pre-push hooks.  :( 

This is my script that i'm running:

```
const target = process.env.npm_lifecycle_event;

console.log('TARGET => ' + target);

if (target === undefined) {
  throw Error('target is not set!');
}
```

Here's my attempt to run the script above with `git push` and then successfully running it via `npm run test`.

<img width="707" alt="screen shot 2017-03-08 at 1 34 17 pm" src="https://cloud.githubusercontent.com/assets/8547391/23725127/38baa670-0404-11e7-9b18-63af526dbf8b.png">

My test repo is here:  https://github.com/sturdynut/prepush-test

**Comment by bebraw** [comment]
I'm not using `process.env.npm_lifecycle_event` anymore. It's weird, though. It would help to know where the actual fault is so we could push the issue upstream.

**Comment by sturdynut** [comment]
Ahh gotcha.  Well, it would be nice to know what is going on.  I followed up on the git-validate [issue](https://github.com/nlf/git-validate/issues/39).  I'm closing this out since it isn't something I can fix in this library.  Sorry for the trouble!
